services:
  mongodb:
    container_name: mongodb-purchase-order-ms
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword