name: Continuos Integration -Testing, Build and Deploy Backend Purchase Order Microservice
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 continuos-integration:
    name: Continuos Integration - Testing and Deploy
    runs-on: ubuntu-latest
    environment: production-purchase-order-microservice
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.X'
      
      - name: Install dependencies with poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Install libs for testing
        run: |
          poetry install
      - name: Run tests unit - Backend Purchase Order Microservice
        run: |
          poetry run pytest   